<?php
declare(strict_types=1);
require_once __DIR__ . '/includes/init.php';

if (!empty($_SESSION['user_id'])) {
    redirect('/dashboard.php');
}

$pageTitle = 'Create Account';
$loginLogo = getLogo('main');
$company = vk_app_setting('company_name', 'VK Network');
$error = '';
$created = null;
$values = [
    'fullname' => '',
    'email' => '',
    'phone' => '',
    'department' => '',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $values = [
        'fullname' => trim((string) ($_POST['fullname'] ?? '')),
        'email' => trim((string) ($_POST['email'] ?? '')),
        'phone' => trim((string) ($_POST['phone'] ?? '')),
        'department' => trim((string) ($_POST['department'] ?? '')),
    ];
    if (!csrf_verify((string) ($_POST['csrf_token'] ?? ''))) {
        $error = 'Your secure registration session expired. Refresh and try again.';
    } else {
        try {
            $created = vk_auth_create_pending_user(db(), $values);
        } catch (Throwable $e) {
            $error = $e instanceof InvalidArgumentException || APP_DEBUG ? $e->getMessage() : 'Unable to create account. Contact support.';
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
    <title><?= e($pageTitle) ?> - <?= e(APP_NAME) ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <link href="<?= e(base_url('assets/css/auth-enterprise.css')) ?>?v=<?= e((string) filemtime(__DIR__ . '/assets/css/auth-enterprise.css')) ?>" rel="stylesheet">
</head>
<body class="vk-auth-body">
<main class="vk-auth-wrap">
    <section class="vk-auth-card" data-signup-wizard aria-labelledby="signupTitle">
        <header class="vk-auth-brand">
            <div class="vk-auth-mark">
                <?php if ($loginLogo !== ''): ?><img src="<?= e($loginLogo) ?>" alt=""><?php else: ?><strong>VK</strong><?php endif; ?>
            </div>
            <div>
                <h1 class="vk-auth-title h2" id="signupTitle"><?= e((string) $company) ?></h1>
                <p class="vk-auth-muted mb-0">Secure Service &amp; Billing Portal Registration</p>
            </div>
        </header>

        <div class="vk-stepper" aria-label="Signup progress">
            <div class="vk-step is-active" data-step-indicator="1"><span>1</span>Identity</div>
            <div class="vk-step" data-step-indicator="2"><span>2</span>Contact</div>
            <div class="vk-step" data-step-indicator="3"><span>3</span>Review</div>
        </div>

        <?php if ($error !== ''): ?>
            <div class="alert alert-danger border-0" role="alert"><i class="bi bi-shield-exclamation me-2"></i><?= e($error) ?></div>
        <?php endif; ?>

        <form method="post" class="needs-validation" novalidate>
            <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">

            <div data-step-pane="1">
                <div class="row g-3">
                    <div class="col-12">
                        <div class="form-floating vk-floating">
                            <input type="text" class="form-control" id="fullname" name="fullname" placeholder="Full name" value="<?= e($values['fullname']) ?>" required minlength="3" maxlength="128" autocomplete="name">
                            <label for="fullname">Full Name</label>
                            <div class="invalid-feedback">Enter your full name.</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="vk-credential-box">
                            <div class="small text-uppercase text-white-50 mb-1">Auto username preview</div>
                            <div class="fw-semibold" id="usernamePreview">Generated after submission</div>
                            <div class="small vk-auth-muted mt-1">Your final username and secure password are generated by the server.</div>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end mt-4">
                    <button type="button" class="btn vk-btn-gradient px-4 py-3" data-step-next>Continue <i class="bi bi-arrow-right ms-2"></i></button>
                </div>
            </div>

            <div class="d-none" data-step-pane="2">
                <div class="row g-3">
                    <div class="col-md-6">
                        <div class="form-floating vk-floating">
                            <input type="text" class="form-control" id="email" name="email" placeholder="Email" value="<?= e($values['email']) ?>" required maxlength="150" autocomplete="email" inputmode="email" pattern="^[^\s@]+@[^\s@]+\.[^\s@]+$">
                            <label for="email">Email Address</label>
                            <div class="invalid-feedback">Enter a valid email address.</div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-floating vk-floating">
                            <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone" value="<?= e($values['phone']) ?>" required minlength="6" maxlength="32" autocomplete="tel">
                            <label for="phone">Phone Number</label>
                            <div class="invalid-feedback">Enter a valid phone number.</div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-floating vk-floating">
                            <input type="text" class="form-control" id="department" name="department" placeholder="Department" value="<?= e($values['department']) ?>" required maxlength="128" list="departmentOptions">
                            <label for="department">Department</label>
                            <datalist id="departmentOptions">
                                <option value="Network Operations">
                                <option value="Billing">
                                <option value="Field Service">
                                <option value="Support Desk">
                                <option value="Management">
                            </datalist>
                            <div class="invalid-feedback">Enter your department.</div>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <button type="button" class="btn btn-outline-light px-4 py-3" data-step-prev><i class="bi bi-arrow-left me-2"></i>Back</button>
                    <button type="button" class="btn vk-btn-gradient px-4 py-3" data-step-next>Review <i class="bi bi-arrow-right ms-2"></i></button>
                </div>
            </div>

            <div class="d-none" data-step-pane="3">
                <div class="vk-credential-box mb-3">
                    <div class="d-flex align-items-start gap-3">
                        <i class="bi bi-shield-lock fs-3 text-info"></i>
                        <div>
                            <h2 class="h5 mb-1">Administrator approval required</h2>
                            <p class="vk-auth-muted mb-0">Your credentials will be generated now, but dashboard access stays locked until an administrator approves the account.</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-between mt-4">
                    <button type="button" class="btn btn-outline-light px-4 py-3" data-step-prev><i class="bi bi-arrow-left me-2"></i>Back</button>
                    <button type="submit" class="btn vk-btn-gradient px-4 py-3" data-loading-text="Generating credentials">Create Account</button>
                </div>
            </div>
        </form>

        <div class="text-center mt-4 small">
            <span class="text-white-50">Already registered?</span>
            <a href="<?= e(BASE_URL) ?>/login.php" class="vk-auth-link fw-semibold ms-1">Sign in</a>
        </div>

        <div id="forgot" class="vk-credential-box mt-4 small">
            <strong><i class="bi bi-life-preserver me-1"></i>Forgot password?</strong>
            <span class="vk-auth-muted">For security, password resets are issued by an administrator from the approval dashboard.</span>
        </div>
    </section>
</main>

<?php if ($created): ?>
<div class="modal fade" id="credentialsModal" tabindex="-1" aria-labelledby="credentialsTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bg-dark text-white border border-info border-opacity-25">
            <div class="modal-header border-info border-opacity-25">
                <h2 class="modal-title h5" id="credentialsTitle"><i class="bi bi-check-circle-fill text-success me-2"></i>Account Created</h2>
                <a class="btn-close btn-close-white" href="<?= e(BASE_URL) ?>/login.php" aria-label="Close"></a>
            </div>
            <div class="modal-body">
                <p class="vk-auth-muted">Save these credentials securely. Your account is waiting for administrator approval.</p>
                <div class="vk-credential-box mb-3">
                    <div class="small text-white-50">User ID</div>
                    <div class="fw-bold" id="credUid"><?= e($created['user_uid']) ?></div>
                </div>
                <div class="vk-credential-box mb-3">
                    <div class="small text-white-50">Username</div>
                    <div class="fw-bold" id="credUsername"><?= e($created['username']) ?></div>
                </div>
                <div class="vk-credential-box">
                    <div class="small text-white-50">Temporary Password</div>
                    <div class="fw-bold" id="credPassword"><?= e($created['password']) ?></div>
                </div>
                <textarea class="visually-hidden" id="allCredentials">VK Network Credentials
User ID: <?= e($created['user_uid']) ?>
Username: <?= e($created['username']) ?>
Password: <?= e($created['password']) ?>
Status: Waiting for administrator approval</textarea>
            </div>
            <div class="modal-footer border-info border-opacity-25">
                <button type="button" class="btn btn-outline-info" data-vk-copy="#allCredentials"><i class="bi bi-copy me-1"></i>Copy credentials</button>
                <button type="button" class="btn btn-outline-light" data-download-credentials><i class="bi bi-filetype-pdf me-1"></i>Download PDF</button>
                <a href="<?= e(BASE_URL) ?>/login.php" class="btn vk-btn-gradient">Go to Sign In</a>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="<?= e(base_url('assets/js/auth-enterprise.js')) ?>?v=<?= e((string) filemtime(__DIR__ . '/assets/js/auth-enterprise.js')) ?>"></script>
<?php if ($created): ?>
<script>
    new bootstrap.Modal(document.getElementById('credentialsModal'), { backdrop: 'static', keyboard: false }).show();
</script>
<?php endif; ?>
</body>
</html>
