-- Key/value app settings (SEO, WhatsApp, SMTP, etc.)
-- Run once on existing databases: import into vk_billing (backup first).

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  key_name VARCHAR(128) NOT NULL,
  value MEDIUMTEXT,
  setting_group VARCHAR(64) NOT NULL DEFAULT 'general',
  setting_type VARCHAR(32) NOT NULL DEFAULT 'text',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_settings_key (key_name),
  KEY idx_settings_group (setting_group)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE settings ADD COLUMN IF NOT EXISTS setting_group VARCHAR(64) NOT NULL DEFAULT 'general' AFTER value;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS setting_type VARCHAR(32) NOT NULL DEFAULT 'text' AFTER setting_group;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER setting_type;

CREATE TABLE IF NOT EXISTS settings_audit_log (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NULL,
  action VARCHAR(64) NOT NULL,
  setting_key VARCHAR(128) NULL,
  value_preview VARCHAR(255) NULL,
  ip_address VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_settings_audit_created (created_at),
  KEY idx_settings_audit_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO settings (key_name, value) VALUES
('site_name', 'VK Network'),
('company_name', 'VK Network'),
('site_title', 'VK Network'),
('company_tagline', 'Multi-Service Solutions'),
('business_slogan', 'Premium local service operations for homes and businesses.'),
('company_logo', ''),
('site_logo', ''),
('site_logo_dark', ''),
('site_logo_light', ''),
('mobile_logo', ''),
('site_favicon', ''),
('contact_phone', '077 887 0135'),
('contact_phone_alt', ''),
('support_email', ''),
('sales_email', ''),
('company_address', '26/3 Thiruvaiyaru, Kilinochchi, Sri Lanka'),
('business_hours', 'Mon - Sat: 8:00 AM - 7:00 PM'),
('google_maps_embed', ''),
('branches_json', '[]'),
('facebook_url', ''),
('instagram_url', ''),
('linkedin_url', ''),
('tiktok_url', ''),
('youtube_url', ''),
('twitter_url', ''),
('hero_title', 'Premium Multi-Service Support, Built Around Trust.'),
('hero_subtitle', 'Book repairs, installations, maintenance, and technical support with real-time tracking and intelligent workflow management.'),
('hero_primary_cta_text', 'Book a Service'),
('hero_primary_cta_url', '/book.php'),
('hero_secondary_cta_text', 'Track My Job'),
('hero_secondary_cta_url', '/track.php'),
('home_stats_json', '[]'),
('services_section_title', 'Expert solutions with fast booking and transparent tracking.'),
('services_section_subtitle', 'Every service is backed by qualified technicians, instant booking, and a seamless customer experience.'),
('testimonials_title', 'Trusted by customers across Sri Lanka.'),
('footer_text', 'Premium local service operations with transparent booking, tracking, and field support for homes and businesses.'),
('footer_bottom_text', 'Made with care in Sri Lanka'),
('navbar_cta_text', 'Book Service'),
('navbar_cta_url', '/book.php'),
('announcement_enabled', '0'),
('announcement_text', ''),
('announcement_url', ''),
('seo_site_title', ''),
('seo_meta_description', 'Professional computer, printer, CCTV, maintenance, and field repair services in Kilinochchi and across Sri Lanka — VK Network.'),
('seo_meta_keywords', 'computer repair, laptop service, printer repair, CCTV installation, Sri Lanka, Kilinochchi, VK Network'),
('seo_og_image', ''),
('seo_twitter_image', ''),
('seo_canonical_url', ''),
('seo_schema_markup', ''),
('robots_txt', 'User-agent: *\nAllow: /'),
('seo_auto_enabled', '1'),
('seo_locations', 'jaffna,vavuniya,kilinochchi'),
('seo_service_slugs', 'computer-repair,laptop-repair,printer-repair,it-service'),
('whatsapp_number', ''),
('whatsapp_default_message', 'Hello VK Network, I would like to inquire about your services.'),
('analytics_domain', ''),
('analytics_script_src', 'https://plausible.io/js/script.js'),
('theme_primary', '#3b82f6'),
('theme_secondary', '#14b8a6'),
('theme_accent', '#a78bfa'),
('theme_gradient_start', '#1e3a8a'),
('theme_gradient_end', '#7c3aed'),
('theme_glow', '#38bdf8'),
('button_style', 'pill'),
('card_style', 'glass'),
('security_maintenance_mode', '0'),
('security_readonly_staff', '1'),
('smtp_host', ''),
('smtp_port', '587'),
('smtp_username', ''),
('smtp_password', ''),
('email_from', '');
